### ISSUE TITLE
Need to explain our use of DAC and reasons behind it

### ISSUE THREAD

**Issue by punkstar** [meanbee/magento-coding-standards#18]

**Comment by tgerulaitis** [comment]
:+1:

I was looking for this today in order to forward it to a junior, refusing to believe that we've missed it out of our standards.

**Comment by brideo** [comment]
Am I forced to use DAC or just the principle?

**Comment by tgerulaitis** [comment]
We use the term "DAC" interchangeably, but in this case it means the procedure of committing an imported template wholesale before making changes to it. It's like using "google" to mean search, we use "dac" to mean this because that's the tool we've been using to do this for a while.

**Comment by tgerulaitis** [comment]
DAC == Duplicate and Commit btw :)

**Comment by brideo** [comment]
+1
